apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasky
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 314146332292.dkr.ecr.us-west-2.amazonaws.com/tasky:~0.0
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/update-strategy: newest-build
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jicowan/tasky.git
    path: helm/tasky-chart
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
