apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasky
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jicowan/tasky.git
    path: helm/tasky-chart
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true